### ISSUE TITLE
 Uncaught TypeError

### ISSUE THREAD

**Issue by edent** [Jeroen-G/Flickr#19]
Getting this error when I try to run the echo test
```
PHP Fatal error:  Uncaught TypeError: Typed property JeroenG\Flickr\Response::$contents must be array, bool used in /home/art/vendor/jeroen-g/flickr/src/Response.php:13
Stack trace:
#0 /home/art/vendor/jeroen-g/flickr/src/Api.php(38): JeroenG\Flickr\Response->__construct(Object(GuzzleHttp\Psr7\Response))
#1 /home/art/vendor/jeroen-g/flickr/src/Flickr.php(16): JeroenG\Flickr\Api->request('flickr.test.ech...', Array)
#2 /home/art/vendor/jeroen-g/flickr/src/Flickr.php(24): JeroenG\Flickr\Flickr->request('flickr.test.ech...', Array)
#3 /home/ar/test.php(11): JeroenG\Flickr\Flickr->echoThis('helloworld')
#4 {main}
  thrown in /home/art/vendor/jeroen-g/flickr/src/Response.php on line 13
```
I've just followed the README. I've added my `$key` as a string.

Have I missed something obvious?

**Comment by Jeroen-G** [comment]
Can you show the code you are trying to execute? And I assume you are running the latest version of this package?
